### ISSUE TITLE
[Bug] 구독인증 메일 링크의 x-webdoc

### ISSUE THREAD

**Issue by onsuk** [Devrother/ironmental-backend#49]
## Description
Apple 기기의 메일 앱에 한정된 버그.

### Error
구독인증 메일 중,
이메일 인증을 하고 다음주 월요일부터 구독을 하고 싶으시다면 [여기]()를 눌러주세요!
-> `여기` 링크를 눌렀을 시, 링크가
x-webdoc://662BAD4D-2B30-4026-A460-498291D2435C/ironmental.net/auth/confirm/{confirmCode}
과 같은 형식으로 변환되기 때문에 제대로 작동하지 않음.

### Expected behaviour
정확한 링크가 전달되어 구독인증이 이루어지는 것.

**Comment by SeungUkLee** [comment]
메일링크 url 에 `https` 가 없으면 `x-webdoc` 가 붙는 것으로 판단되어 메일링크 url 에 https 를 붙여서 인증메일을 보내어 확인한 결과 잘 작동함

### Reference
[Problem with additional links in Event Confirmation email
](https://forum.civicrm.org/index.php%3Ftopic=32515.0.html)
